linters-settings:
  govet:
    enable-all: true
    disable:
      - shadow

linters:
  enable-all: true
  disable:
    - copyloopvar  # Go 1.22+ feature, not compatible with Go 1.18
    - dogsled
    - dupl
    - exhaustive
    - errorlint
    - err113       # renamed from goerr113 (deprecated)
    - forbidigo
    - funlen
    - gci
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofumpt
    - gosec
    - intrange     # Go 1.22+ feature, not compatible with Go 1.18
    - lll
    - mnd
    - makezero
    - nakedret
    - nestif
    - nlreturn
    - paralleltest
    - perfsprint
    - tenv         # deprecated, replaced by usetesting
    - testpackage
    - thelper
    - wrapcheck
    - wsl
    - varnamelen
    - nilnil
    - ireturn
    - govet
    - forcetypeassert
    - cyclop
    - containedctx
    - revive
    - exhaustruct
    - depguard

issues:
  exclude-files:
    - encode_optype.go
    - ".*_test\\.go$"
  exclude-rules:
    # not needed
    - path: /*.go
      text: "ST1003: should not use underscores in package names"
      linters:
        - stylecheck
    - path: /*.go
      text: "don't use an underscore in package name"
      linters:
        - golint
    - path: rtype.go
      linters:
        - golint
        - stylecheck
    - path: error.go
      linters:
        - staticcheck

  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0

  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0
